### ISSUE TITLE
Show pression with better precision

### ISSUE THREAD

**Issue by giomasce** [jenslody/gnome-shell-extension-openweather#110]
Hi.

I would like to read pressure in bars, but unfortunately the Openweather extension would use no digits after the decimal point. This is useless, because pressure in bars is more or less always 1 bar, so digits after the point are really required.

In case it could be that, I am using the Italian locale.

Thanks.

**Comment by jenslody** [comment]
The problem is, that I use the same settings for max-digits after comma for all values.
And this setting defaults to "1", but a precision of one digit will in many cases be rounded to zero and not shown in this case.
As a workaround you can set the value to "2" or "3", but this also affects the temeperatures, where it does not make real sense.
I use hPa instead of Bar what is in fact mBar and can be of use for you also.
