### ISSUE TITLE
Cannot change location

### ISSUE THREAD

**Issue by aswinmuralidharan** [jenslody/gnome-shell-extension-openweather#158]
Hi, I am running OpenSuse 42.1 Gnome edition and I tried the openweather extension. It works great except that I cant change my default location. Hence the weather shown is always the weather from Vaiaku, Tuvalu.

**Comment by jenslody** [comment]
What exactly does not work ?
How do you try to change the location ?

**Comment by aswinmuralidharan** [comment]
I try to change location from the the gnome extension shell preferences. But there is no option where I can change my location.

**Comment by jenslody** [comment]
If you click on the icon/temperature in the panel you get a pop up menu with the forecasts for the next days.
In the bottom, there are three buttons, the left is to chose locations (if configured), the middle (second left) is to reload and the rightmost button opens the preferences dialog.
Here you can add, remove edit locations and do all the other configuration stuff. It should be self-explaining.
If you don't see the button to add, remove, edit locations, you might need to scroll (or resize) the dialog.

**Comment by Happyfeet01** [comment]
i also can add my location. Must we use a geolocation Provider or can we manualy add a city?
![wetter](https://cloud.githubusercontent.com/assets/3295104/19263018/6e081774-8f9a-11e6-8185-0e7b863da840.png)

Ubuntu 16.04 LTS
Gnome Desktop

**Comment by jenslody** [comment]
The default geolocation provider is free, so you can use it without api-key.
You can of course also edit any location, but it will overwrite the existing one, there is no "Save as".
If you edit it, you have to know the correct longitude and latitude.

**Comment by caboteria** [comment]
The problem is that the configuration window is too small by default so the + - and edit buttons at the bottom left are hidden (at least on Fedora 25).  Note the dashed line at the bottom of the snapshot in Happyfeet01's comment above.  There's also one on the right side which indicates that part of the window at the bottom is obscured.  If you drag the bottom window border down, then the window will expand vertically and the + - and edit buttons will become visible and you can use them to add locations.

**Comment by glaubersm** [comment]
Default window size should to be enough to user to see the whole GUI.

**Comment by jenslody** [comment]
Closed,  see #172 .
