### ISSUE TITLE
Need gnome 3.24 compatibility

### ISSUE THREAD

**Issue by dino99** [jenslody/gnome-shell-extension-openweather#177]
Ubuntu Zesty now use 3.23.90 (3.24) gnome-shell
and that extension does not support it yet;

GNOME Shell 3.24 now uses mozjs38 (SpiderMonkey 38) which has stricter syntax rules.
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey
 please do asap
Thanks

**Comment by jenslody** [comment]
The extension (now) supports 3.24.
Despite this, version check validation is disabled as default since nearly half a year now by gnome itself.
So it should not be a problem with ubuntu.
And if it is, there's nothing I can (want to) do.

Do you have any issues due to the syntax in my extension ?
If yes, could you please be a little bit more specific ?
I don't see any relevant messages in Fedora Rawhide, neither when working with the extension, nor when enabling/disabling it via gnome-tweak-tools.

**Comment by greatquux** [comment]
is the extension verison on https://extensions.gnome.org updated to a version that now supports 3.24? when i try to install, i click to ON, it asks if i want to install and i press the install button, and it moves to ON but nothing happens and if i refresh the page it goes back to OFF.

**Comment by jenslody** [comment]
I just uploaded a new revision to extensions.gnome.org for review, that should really fix this issue.
If you want to test it, before it is gone through review, you can download the zip-file directly and install it via gnome-tweak-tool: https://extensions.gnome.org/review/download/6637.shell-extension.zip

**Comment by greatquux** [comment]
I just installed from the ZIP and it works great, thank you!
