### ISSUE TITLE
Translated strings show up in English instead of the chosen language

### ISSUE THREAD

**Issue by pizzamaker** [jenslody/gnome-shell-extension-openweather#87]
There are several strings that have been translated into Portuguese but keep showing up as English, such as 'In two days' or most of the strings in the Settings window.

**Comment by jenslody** [comment]
If a translation for a string, still has the fuzzy-keyword in a comment, it will  not be shown.
This is also stated in the wiki.
If I add (or merge) translations of languages I do not speak myself, I have to rely on the translators, so I can (and will) not remove these lines myself, because I can not decide whether a translation is correct or not. 
Sorry !
